### ISSUE TITLE
Crash dump

### ISSUE THREAD

**Issue by chrislachance** [RedShyGuy/Vapecord-ACNL-Plugin#17]
Trying to apply to ACNL (cartridge), getting crash dump message.
![PXL_20201111_021848368](https://user-images.githubusercontent.com/1014935/98757372-6583bc00-239a-11eb-9836-ce352165259b.jpg)

**Comment by SirEnder125** [comment]
This is from a noob's point of view, but,

1. maybe you have the wrong region of the plugin installed?

2. possibly it's not the plugin itself but a file not properly 
placed such as the text files needed?

3. You could try disabling Arm11 exception handler in Luma3ds
config menu. (Not sure if this is a good idea since it has a warning.)

**Comment by RedShyGuy** [comment]
It seems it did not even crash the game itself due to the current process not being ACNL. You can try to reinstall the plugin to try again! Make sure you have the Welcome Amiibo Update as it does not work with old versions of ACNL!

**Comment by 290604Tom** [comment]
Hi! I have the same problem and I tried to reinstall, I have the correct version. So I don't understand what's wrong.

**Comment by RedShyGuy** [comment]
Do you maybe have 2 plugins in the same directory?
