### ISSUE TITLE
Can’t pick up items from the ground

### ISSUE THREAD

**Issue by PianoHarmony** [RedShyGuy/Vapecord-ACNL-Plugin#27]
Hi! I’m back. I just installed the new update to the plug-in, and I’m getting a very weird glitch. I can’t pick up flowers or weeds from the ground, and if I try to pick up an item it just vanishes! This happened with Wisp’s lamp (which isn’t a big deal because I can just spawn a new one probably), but it’s been happening with every other item from the ground. If needed I can list what cheats I have enabled. Please help if you can!

**Comment by RedShyGuy** [comment]
![Screenshot_20210108-030505_Discord.jpg](https://user-images.githubusercontent.com/43783060/103965587-57fe6e80-515e-11eb-80b6-64cfd654b48e.jpg)
These here are some of the known issues, I should really put them onto github somewhere (sorry). So it is known that picking up stuff doesnt work if the 3ds is closed/reopened (same thing happens if you go to the home menu and back) The next version will fix these issues! Sorry for all the inconviniences!!

**Comment by SirEnder125** [comment]
Turning on pluck mode with seeder sometimes helps when
picking up certain items.

**Comment by RedShyGuy** [comment]
The bug breaks pickup completely, so doesnt matter which mode is active, even having the pickup seeder off.
