### ISSUE TITLE
Plugin seems to abort after crash on online island.

### ISSUE THREAD

**Issue by SirEnder125** [RedShyGuy/Vapecord-ACNL-Plugin#71]
After a crash on the online island, the plugin 'aborts'. Which, usually, shows an orange top screen and bottom screen, this time it did not. The menu would not open and no cheats could be disabled. (And map player icons disappeared due to the hack that lets you see others on map.)

**Comment by RedShyGuy** [comment]
With crash on the online island do you mean a lost connection error?

**Comment by SirEnder125** [comment]
Yes, a lost connection. With the reset animal guy.

**Comment by BioHazard1282** [comment]
For me whenever I am playing online at an island or in another town (online), whenever something happens and it disconnects, Luma3DS exits out with an `ErrorDisp`. Now usually I can just press a button to reboot, but I have to force my 3DS off because it just hangs there, it's like a blue screen that won't restart
