### ISSUE TITLE
Lyle disappeared when using player loader

### ISSUE THREAD

**Issue by Nova190** [RedShyGuy/Vapecord-ACNL-Plugin#94]
I can't unlock storage and stuff, I also don't know how to get him back, his desk is still there though

**Comment by SirEnder125** [comment]
I'm not sure if I understand the problem here, but I want to make it clear that, unlocking Lyle in one account on ACNL will not make it so that he will be there in every account. Make sure that you have gone back to the account in which you originally saw Lyle there in. If his desk is there, he also should be, unless you are in a different account.

**Comment by Nova190** [comment]
so I went from account 1, who had lyle unlocked, to account 2 who didn't, and when i went back to account 1 he was gone and he hasn't come back since

**Comment by RedShyGuy** [comment]
Player loader doesn't fully load your other players, it doesn't work perfect yet

**Comment by Nova190** [comment]
oh okay, do you know how I could get him back?

**Comment by RedShyGuy** [comment]
Reload a older save file before it happaned
